# runtime: nodejs20
# env: standard
# service: elicitafrontend   # frontend service name
# entrypoint: serve -s build -l $PORT

# instance_class: F2

# env_variables:
#   NODE_ENV: "production"
#   REACT_APP_BACKEND_URL: "https://elicita-backend-dot-theta-messenger-459613-p7.el.r.appspot.com"


# runtime: nodejs20
# service: elicitafrontend
# instance_class: F2

# entrypoint: npm start

# env_variables:
#   NODE_ENV: "production"
#   REACT_APP_BACKEND_URL: "https://elicita-backend-dot-theta-messenger-459613-p7.el.r.appspot.com"


runtime: nodejs20
env: standard
service: elicita-2-0
entrypoint: npx serve -s dist -l $PORT

instance_class: F1   # smallest & cheapest

automatic_scaling:
  min_instances: 0
  max_instances: 1
  min_idle_instances: 0
  max_idle_instances: 0
  target_cpu_utilization: 0.85
  max_pending_latency: 5000ms
